### ISSUE TITLE
Actor component cleanup.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1751]
My proposal for cleaning up BasicActorComponent and IActorComponent is the following,
- [x] Remove IActorComponent. (#1752)
- [x] Remove PlayerAttachedMsg and PlayerDetachedMsg component messages. (#1832)
- [x] Rename PlayerAttachSystemMessage to PlayerAttachedEvent. (#1774)
- [x] Rename PlayerDetachedSystemMessage to PlayerDetachedEvent. (#1774)
- [x] Rename BasicActorComponent to ActorComponent. (#1752)
- [x] Create ActorSystem to handle players being attached to entities, and detached from them in an ECS manner. (#1774)

There's an awful antipattern lingering in our codebase, and that is having useless interfaces that only a single class will *ever* inherit. Content code will be split between using the interface and the actual class implementing it, and spaghetti will ensure.
