### ISSUE TITLE
Rich Text TODO list

### ISSUE THREAD

**Issue by Efruit** [space-wizards/RobustToolbox#2349]
don't mind me, just @Efruit's TODO list

- [ ] Markup _2_
    - [ ] Markdown? (Markup _**3**_)
- [ ] `internal`-ize `FormattedMessage.Builder`
- [ ] Write a real Serializer
    - [ ] Include a way to bundle `FluentArgs`
- [ ] #2273 (blocked by ↑)
- [x] ~~Fix the damn descent issue~~ (#2351)
- [ ] Word splitting (#2352)
- [ ] Clean up warnings (#2343)
- [ ] Test/tweak the various (presently-unused) layout features
- [ ] Performance improvements (mainly reducing allocations in `Layout` and friends)
- [ ] #2101 (blocked waiting for #2352)

**Comment by Efruit** [comment]
OBE #2363
